import React from 'react'
import { motion } from 'framer-motion'
import { ArrowLeft } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: 'easeOut' } },
}

export default function TermsOfService() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-surface-900 text-white">
      <div className="container mx-auto px-6 py-12 max-w-4xl">
        <motion.button
          onClick={() => navigate('/')}
          className="flex items-center gap-2 text-brand-400 hover:text-brand-300 mb-8 transition-colors"
          variants={fadeUp}
          initial="hidden"
          animate="visible"
        >
          <ArrowLeft className="w-5 h-5" />
          Back to Home
        </motion.button>

        <motion.div variants={fadeUp} initial="hidden" animate="visible">
          <h1 className="text-4xl font-bold mb-8 text-center">Terms of Service</h1>

          <div className="prose prose-invert max-w-none">
            <p className="text-lg mb-6">
              <strong>Effective Date:</strong> March 16, 2026
            </p>

            <p className="mb-6">
              These Terms of Service ("Terms") govern your use of PharmForge AI, an AI-powered drug discovery platform. By accessing or using our services, you agree to be bound by these Terms.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By creating an account or using PharmForge AI, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">2. Description of Service</h2>
            <p className="mb-4">
              PharmForge AI provides AI-powered tools for drug discovery, including:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>De novo molecule generation from protein sequences</li>
              <li>ADMET property prediction</li>
              <li>Lead optimization and analysis</li>
              <li>Research data management and visualization</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">3. User Eligibility</h2>
            <p className="mb-4">
              Our services are intended for researchers, scientists, and professionals in the pharmaceutical and biotechnology industries. You must be at least 18 years old and have the legal capacity to enter into these Terms.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">4. Account Registration and Security</h2>
            <p className="mb-4">
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">5. Token System and Usage Limits</h2>
            <p className="mb-4">
              Our platform operates on a token-based system:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>Free tier provides limited tokens for evaluation</li>
              <li>Paid plans offer additional tokens for extended usage</li>
              <li>Tokens are non-transferable and expire according to plan terms</li>
              <li>Excessive usage may result in temporary service limitations</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">6. Payment Terms</h2>
            <p className="mb-4">
              Payment processing is handled through Razorpay. All fees are non-refundable except as required by law. Subscription renewals are automatic unless cancelled.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">7. Intellectual Property</h2>
            <h3 className="text-xl font-medium mt-6 mb-3">7.1 Our Intellectual Property</h3>
            <p className="mb-4">
              PharmForge AI and its underlying technology, including AI models, algorithms, and software, are protected by intellectual property laws. You may not copy, modify, or reverse engineer our platform.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">7.2 User Content</h3>
            <p className="mb-4">
              You retain ownership of data you upload to our platform. By using our services, you grant us a limited license to process and analyze your data for providing the service.
            </p>

            <h3 className="text-xl font-medium mt-6 mb-3">7.3 Generated Results</h3>
            <p className="mb-4">
              Results generated by our AI models are provided for research purposes. You are responsible for validating and verifying all scientific findings.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">8. Acceptable Use Policy</h2>
            <p className="mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Use the service for illegal purposes</li>
              <li>Attempt to circumvent usage limits or security measures</li>
              <li>Share account credentials or tokens</li>
              <li>Upload malicious code or harmful data</li>
              <li>Violate intellectual property rights</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">9. Data Privacy and Security</h2>
            <p className="mb-4">
              We implement industry-standard security measures to protect your data. However, you acknowledge that no system is completely secure. See our Privacy Policy for detailed information.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">10. Disclaimers and Limitations</h2>
            <p className="mb-4">
              OUR SERVICES ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. WE DO NOT GUARANTEE THE ACCURACY, COMPLETENESS, OR RELIABILITY OF AI-GENERATED RESULTS. DRUG DISCOVERY INVOLVES SIGNIFICANT RISKS, AND YOU ASSUME ALL RESPONSIBILITY FOR USING OUR RESULTS IN RESEARCH OR DEVELOPMENT.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">11. Limitation of Liability</h2>
            <p className="mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, PHARMFORGE AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OUR SERVICES.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">12. Termination</h2>
            <p className="mb-4">
              We may terminate or suspend your account for violations of these Terms. Upon termination, your right to use the service ceases immediately.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">13. Governing Law</h2>
            <p className="mb-4">
              These Terms are governed by the laws of India. Any disputes shall be resolved in the courts of Mumbai, Maharashtra.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">14. Changes to Terms</h2>
            <p className="mb-4">
              We may modify these Terms at any time. Continued use of our services constitutes acceptance of updated Terms.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">15. Contact Information</h2>
            <p className="mb-4">
              For questions about these Terms, please contact us at legal@pharmforge.ai or through our contact form.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  )
}